---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hello-world-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 512M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/ok/boomer"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hello-world-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512M