---
apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  volumes:
    - name: hello-world-storage
      persistentVolumeClaim:
        claimName: hello-world-claim
  containers:
    - name: hello-world
      image: samber/hello-world-nodejs
      env:
      - name: PORT
        value: "8080"
      ports:
        - containerPort: 8080